### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by koriavinash1** [debayanmitra1993-data/Blindness-Detection-Diabetic-Retinopathy-#1]
hey @debayanmitra1993-data,
        Can you upload the trained model and a few example images (each class) to the repo? It would be really helpful...

Thank you,
Avinash

**Comment by debayanmitra1993-data** [comment]
Hi @koriavinash1  - You can find the example images here - https://www.kaggle.com/c/aptos2019-blindness-detection/data

**Comment by koriavinash1** [comment]
cool got it
